GET http://localhost:8080/TouristGuide_war_exploded/api/article
Accept: application/json

###

###ARTICLE
POST http://localhost:8080/TouristGuide_war_exploded/api/article
Content-Type: application/json

{
  "title": "Sample Article",
  "text": "This is the content of the article.",
  "autor_id": 4,
  "destination_id": 7,
  "tags": [1, 2, 3, 4, 5]
}

###
DELETE http://localhost:8080/TouristGuide_war_exploded/api/article/4
###
GET http://localhost:8080/TouristGuide_war_exploded/api/article/3
Accept: application/json





###USER
POST http://localhost:8080/TouristGuide_war_exploded/api/user/login
Content-Type: application/json

{
  "email" : "sample@email.com",
  "password": "password"
}


###
GET http://localhost:8080/TouristGuide_war_exploded/api/user
Accept: application/json

###
POST http://localhost:8080/TouristGuide_war_exploded/api/user
Content-Type: application/json

{
  "firstname":"Danilo",
  "lastname": "Joncic",
  "tip": "admin",
  "email" : "mail@email.com",
  "password": "pass"
}
###
POST http://localhost:8080/TouristGuide_war_exploded/api/user/login
Content-Type: application/json

{
  "email" : "writer@mail.com",
  "password": "written"
}
###
POST http://localhost:8080/TouristGuide_war_exploded/api/user/login
Content-Type: application/json

{
  "email" : "blocked@mail.com",
  "password": "badsport"
}
###DESTINATION
###
POST http://localhost:8080/TouristGuide_war_exploded/api/destination
Content-Type: application/json

{
  "name" : "Paris",
  "description" : "City of light"
}

###
DELETE http://localhost:8080/TouristGuide_war_exploded/api/destination/8

###
GET http://localhost:8080/TouristGuide_war_exploded/api/destination
Accept: application/json

###
GET http://localhost:8080/TouristGuide_war_exploded/api/destination
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaXJzdG5hbWUiOiJXcml0ZXIiLCJ0aXAiOiJlZGl0b3IiLCJsYXN0bmFtZSI6Ik1jV3JpdHRpbmcifQ.HRh5SQwcBREsVgJF86xDnl3I31yWir4yj_ZgDWpNvQE

###
PUT http://localhost:8080/TouristGuide_war_exploded/api/destination/2
Content-Type: application/json

{
  "name": "Updated Post Title",
  "description": "This is an updated post description"
}


###ACTIVITY
###
POST http://localhost:8080/TouristGuide_war_exploded/api/activity
Content-Type: application/json

{
  "tag" : "Sample activity"
}

###
DELETE http://localhost:8080/TouristGuide_war_exploded/api/activity/6

###
GET http://localhost:8080/TouristGuide_war_exploded/api/activity/1
Accept: application/json

###
GET http://localhost:8080/TouristGuide_war_exploded/api/activity
Accept: application/json

###
PUT http://localhost:8080/TouristGuide_war_exploded/api/activity/5
Content-Type: application/json

{
  "tag": "Diving"
}
###








